services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: jolly1228
    ports:
      - "8080:80"

volumes:
  db-data:
